[package]
name = "raytracer"
version = "0.1.0"
authors = ["Daniel Wayota <danielglez1990@gmail.com>"]
edition = "2018"

[lib]
name = "raytracer"
path = "src/lib.rs"

[dependencies]
rand = "0.6.5"
bmp = "*"

[dev-dependencies]
minifb = "0.11.2"