[package]
name = "raytracer"
version = "0.1.0"
authors = ["Daniel Wayota <danielglez1990@gmail.com>"]
edition = "2018"

[[bin]]
name = "raytracer"
path = "src/main.rs"

[dependencies]
rand = "0.6.5"
bmp = "*"
minifb = "0.11.2"
